package com.mikaservices.platform.modules.qshe.enums

enum class TypeEpi {
    CASQUE,
    LUNETTES,
    VISIERE,
    BOUCHONS_OREILLES,
    CASQUE_ANTIBRUIT,
    MASQUE_POUSSIERE,
    DEMI_MASQUE,
    MASQUE_COMPLET,
    GANTS_MECANIQUES,
    GANTS_CHIMIQUES,
    GANTS_THERMIQUES,
    CHAUSSURES_SECURITE,
    GILET_HAUTE_VISIBILITE,
    HARNAIS_ANTICHUTE,
    LONGE,
    ENROULEUR,
    VETEMENT_TRAVAIL,
    TABLIER_SOUDEUR,
    AUTRE
}
