package com.mikaservices.platform.common.enums

enum class MotifArretChantier {
    // Climatiques et naturelles
    FORTES_PLUIES,
    INONDATION,
    SOL_SATURE,
    GLISSEMENT_TERRAIN,
    CRUE_RIVIERE,
    CHALEUR_EXTREME,
    FOUDRE_ORAGE,
    VEGETATION_ENVAHISSANTE,

    // Administratives et réglementaires
    RETARD_PERMIS_CONSTRUIRE,
    ABSENCE_AUTORISATION_SOL,
    NON_CONFORMITE_URBANISME,
    ARRETE_PREFECTORAL,
    RETARD_ETUDE_IMPACT,
    PROBLEME_MARCHE_PUBLIC,
    CHANGEMENT_GOUVERNEMENT,
    AUDIT_COUR_COMPTES,

    // Financières
    RETARD_PAIEMENT_MAITRE_OUVRAGE,
    INSUFFISANCE_TRESORERIE,
    GEL_BUDGETAIRE,
    NON_OBTENTION_CAUTION,
    LITIGE_DECOMPTES,
    DEPASSEMENT_BUDGET,
    DEFAILLANCE_SOUS_TRAITANT,

    // Logistiques et approvisionnement
    RUPTURE_STOCK_CIMENT,
    RETARD_LIVRAISON_PORT,
    BLOCAGE_DOUANE,
    INDISPONIBILITE_GRANULATS,
    PANNE_ENGIN_SANS_PIECES,
    ROUTES_IMPRATICABLES,
    PENURIE_CARBURANT,
    COUPURE_ELECTRICITE,
    PENURIE_EAU,

    // Techniques et qualité
    ERREUR_ETUDES_TECHNIQUES,
    MODIFICATION_PROJET_AVENANT,
    MALFACON_DEMOLITION,
    DECOUVERTE_RESEAUX_ENTERRES,
    SOL_FONDATION_NON_CONFORME,
    DEFAILLANCE_EQUIPEMENT,

    // Sociales et humaines
    CONFLIT_FONCIER,
    OPPOSITION_RIVERAINS,
    GREVE_OUVRIERS,
    PENURIE_MAIN_OEUVRE,
    ACCIDENT_GRAVE,
    EPIDEMIE_CRISE_SANITAIRE,
    PROBLEME_VISA_MAIN_OEUVRE,

    // Sécuritaires et force majeure
    INSECURITE_VOL_MATERIAUX,
    DECOUVERTE_MUNITIONS,
    ORDRE_AUTORITE_SECURITE,

    // Environnementales
    ESPECE_PROTEGEE_ZONE_CLASSEE,
    POLLUTION_ACCIDENTELLE,
    NON_RESPECT_PRESCRIPTIONS_ENV,

    // Contractuelles et juridiques
    RESILIATION_MAITRE_OEUVRE,
    LIQUIDATION_JUDICIAIRE,
    LITIGE_PARTENAIRES_GROUPEMENT,
    EXPIRATION_ORDRE_SERVICE,

    // Autre
    AUTRE
}
