// En prod (Render), définir VITE_API_BASE_URL (ex. https://mika-services-api.onrender.com/api)
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? '/api'
export const API_VERSION = 'v1'

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_POLICY: '/auth/login-policy',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_2FA: '/auth/verify-2fa',
    '2FA_SETUP': '/auth/2fa/setup',
    '2FA_VERIFY_SETUP': '/auth/2fa/verify-setup',
    '2FA_DISABLE': '/auth/2fa/disable',
    ME: '/users/me',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: number) => `/users/${id}`,
    BY_EMAIL: (email: string) => `/users/email/${email}`,
    ME: '/users/me',
    ME_PHOTO: '/users/me/photo',
    PHOTO_BY_ID: (id: number) => `/users/${id}/photo`,
    AUDIT_LOGS: (id: number) => `/users/${id}/audit-logs`,
    CHANGE_PASSWORD: (id: number) => `/users/${id}/password`,
  },
  EQUIPES: {
    BASE: '/equipes',
    BY_ID: (id: number) => `/equipes/${id}`,
    AFFECTATIONS_BY_USER: (userId: number) => `/equipes/affectations/user/${userId}`,
  },
  ROLES: {
    BASE: '/roles',
    ACTIVE: '/roles/active',
    BY_ID: (id: number) => `/roles/${id}`,
    BY_CODE: (code: string) => `/roles/code/${code}`,
    ADD_PERMISSION: (roleId: number, permissionId: number) => `/roles/${roleId}/permissions/${permissionId}`,
    REMOVE_PERMISSION: (roleId: number, permissionId: number) => `/roles/${roleId}/permissions/${permissionId}`,
  },
  PROJETS: {
    BASE: '/projets',
    BY_ID: (id: number) => `/projets/${id}`,
    SEARCH: '/projets/search',
    BY_STATUT: (statut: string) => `/projets/statut/${statut}`,
    BY_RESPONSABLE: (userId: number) => `/projets/responsable/${userId}`,
    COUNT_BY_STATUT: (statut: string) => `/projets/count/${statut}`,
    AVANCEMENT_ETUDES: (id: number) => `/projets/${id}/avancement-etudes`,
    PREVISIONS: (id: number) => `/projets/${id}/previsions`,
    PREVISION_BY_ID: (projetId: number, previsionId: number) => `/projets/${projetId}/previsions/${previsionId}`,
    HISTORIQUE: (id: number) => `/projets/${id}/historique`,
    SUIVI_MENSUEL: (id: number) => `/projets/${id}/suivi-mensuel`,
    SUIVI_MENSUEL_REPLACE: (id: number) => `/projets/${id}/suivi-mensuel/replace`,
    ANALYSE_RAPPORT: (id: number) => `/projets/${id}/analyse-rapport`,
  },
  SOUS_PROJETS: {
    BASE: '/sous-projets',
    BY_ID: (id: number) => `/sous-projets/${id}`,
    BY_PROJET: (projetId: number) => `/sous-projets/projet/${projetId}`,
  },
  CLIENTS: {
    BASE: '/clients',
    BY_ID: (id: number) => `/clients/${id}`,
    BY_CODE: (code: string) => `/clients/code/${code}`,
    SEARCH: '/clients/search',
  },
  POINTS_BLOQUANTS: {
    BASE: '/points-bloquants',
    BY_ID: (id: number) => `/points-bloquants/${id}`,
    BY_PROJET: (projetId: number) => `/points-bloquants/projet/${projetId}`,
    BY_STATUT: (statut: string) => `/points-bloquants/statut/${statut}`,
    BY_ASSIGNE: (userId: number) => `/points-bloquants/assigne/${userId}`,
  },
  PLANNING: {
    TACHES: '/planning/taches',
    TACHE_BY_ID: (id: number) => `/planning/taches/${id}`,
    BY_PROJET: (projetId: number) => `/planning/taches/projet/${projetId}`,
    MES_TACHES: (userId: number) => `/planning/taches/mes-taches/${userId}`,
    EN_RETARD: '/planning/taches/en-retard',
  },
  DOCUMENTS: {
    BASE: '/documents',
    BY_ID: (id: number) => `/documents/${id}`,
    BY_PROJET: (projetId: number) => `/documents/projet/${projetId}`,
    ME_CV: '/documents/me/cv',
    DOWNLOAD: (id: number) => `/documents/${id}/download`,
  },
  REPORTING: {
    DASHBOARD: '/reporting/dashboard',
    PROJET_REPORT: (projetId: number) => `/reporting/projet/${projetId}`,
  },
  MESSAGES: {
    ENVOYER: (expediteurId: number) => `/messages/${expediteurId}`,
    RECUS: (userId: number) => `/messages/recus/${userId}`,
    ENVOYES: (userId: number) => `/messages/envoyes/${userId}`,
    CONVERSATION: (userId1: number, userId2: number) => `/messages/conversation/${userId1}/${userId2}`,
    MARQUER_LU: (messageId: number, userId: number) => `/messages/${messageId}/lu/${userId}`,
    NON_LUS: (userId: number) => `/messages/non-lus/${userId}`,
    DELETE: (messageId: number) => `/messages/${messageId}`,
    ENVOYER_AVEC_PIECES: (expediteurId: number) => `/messages/${expediteurId}/with-attachments`,
    PIECE_JOINTE_DOWNLOAD: (pieceJointeId: number, userId: number) =>
      `/messages/pieces-jointes/${pieceJointeId}/download?userId=${userId}`,
    ARCHIVE: '/messages/archive',
    UNARCHIVE: '/messages/unarchive',
    ARCHIVED_PEERS: (userId: number) => `/messages/archived-peers/${userId}`,
    SUPPRESS_FOR_ME: (messageId: number) => `/messages/${messageId}/suppress-for-me`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    MES_NOTIFICATIONS: (userId: number) => `/notifications/mes-notifications/${userId}`,
    NON_LUES: (userId: number) => `/notifications/non-lues/${userId}`,
    MARQUER_LUE: (notifId: number, userId: number) => `/notifications/${notifId}/lu/${userId}`,
    TOUT_LU: (userId: number) => `/notifications/tout-lu/${userId}`,
    COUNT: (userId: number) => `/notifications/count/${userId}`,
    DELETE: (notifId: number) => `/notifications/${notifId}`,
  },
  QSHE_ENVIRONNEMENT: {
    MESURES: '/qshe/environnement/mesures',
    MESURES_BY_PROJET: (projetId: number) => `/qshe/environnement/mesures/projet/${projetId}`,
    DECHETS: '/qshe/environnement/dechets',
    DECHETS_BY_PROJET: (projetId: number) => `/qshe/environnement/dechets/projet/${projetId}`,
    PRODUITS: '/qshe/environnement/produits',
    PRODUIT_BY_ID: (id: number) => `/qshe/environnement/produits/${id}`,
    SUMMARY: (projetId: number) => `/qshe/environnement/summary/projet/${projetId}`,
  },
  QSHE_PERMIS: {
    BASE: '/qshe/permis',
    BY_ID: (id: number) => `/qshe/permis/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/permis/projet/${projetId}`,
    SUMMARY: (projetId: number) => `/qshe/permis/summary/projet/${projetId}`,
  },
  QSHE_CAUSERIES: {
    BASE: '/qshe/causeries',
    BY_ID: (id: number) => `/qshe/causeries/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/causeries/projet/${projetId}`,
    SUMMARY: (projetId: number) => `/qshe/causeries/summary/projet/${projetId}`,
  },
  QSHE_EPI: {
    BASE: '/qshe/epi',
    BY_ID: (id: number) => `/qshe/epi/${id}`,
    BY_USER: (userId: number) => `/qshe/epi/user/${userId}`,
    EXPIRES: '/qshe/epi/expires',
    STOCK_BAS: '/qshe/epi/stock-bas',
    SUMMARY: '/qshe/epi/summary',
  },
  QSHE_CERTIFICATIONS: {
    BASE: '/qshe/certifications',
    BY_ID: (id: number) => `/qshe/certifications/${id}`,
    BY_USER: (userId: number) => `/qshe/certifications/user/${userId}`,
    EXPIRANT: '/qshe/certifications/expirant',
    EXPIREES: '/qshe/certifications/expirees',
    SUMMARY: '/qshe/certifications/summary',
  },
  QSHE_INCIDENTS: {
    BASE: '/qshe/incidents',
    BY_ID: (id: number) => `/qshe/incidents/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/incidents/projet/${projetId}`,
    STATUT: (id: number) => `/qshe/incidents/${id}/statut`,
    SUMMARY: (projetId: number) => `/qshe/incidents/summary/projet/${projetId}`,
    CNSS_EN_RETARD: '/qshe/incidents/declarations-cnss-en-retard',
  },
  QSHE_RISQUES: {
    BASE: '/qshe/risques',
    BY_ID: (id: number) => `/qshe/risques/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/risques/projet/${projetId}`,
    SUMMARY: (projetId: number) => `/qshe/risques/summary/projet/${projetId}`,
  },
  QSHE_INSPECTIONS: {
    BASE: '/qshe/inspections',
    BY_ID: (id: number) => `/qshe/inspections/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/inspections/projet/${projetId}`,
    TEMPLATES: '/qshe/inspections/templates',
    TEMPLATE_BY_ID: (id: number) => `/qshe/inspections/templates/${id}`,
  },
  QSHE_DASHBOARD: {
    BY_PROJET: (projetId: number) => `/qshe/dashboard/projet/${projetId}`,
  },
  QSHE_REPORT: {
    BY_PROJET: (projetId: number) => `/qshe/report/projet/${projetId}`,
  },
  QSHE_ACTIONS: {
    BASE: '/qshe/actions',
    BY_ID: (id: number) => `/qshe/actions/${id}`,
    BY_PROJET: (projetId: number) => `/qshe/actions/projet/${projetId}`,
    BY_SOURCE: (sourceType: string, sourceId: number) => `/qshe/actions/source/${sourceType}/${sourceId}`,
    EN_RETARD: '/qshe/actions/en-retard',
    SUMMARY: (projetId: number) => `/qshe/actions/summary/projet/${projetId}`,
  },
  REUNIONS_HEBDO: {
    BASE: '/reunions-hebdo',
    BY_ID: (id: number) => `/reunions-hebdo/${id}`,
    BY_STATUT: (statut: string) => `/reunions-hebdo/statut/${statut}`,
    POINTS_PROJET: (reunionId: number) => `/reunions-hebdo/${reunionId}/points-projet`,
    POINT_PROJET: (reunionId: number, pointId: number) => `/reunions-hebdo/${reunionId}/points-projet/${pointId}`,
  },
  AUDIT: {
    PAGE_VIEW: '/audit/page-view',
    GLOBAL: '/audit/global',
    STATS: '/audit/stats',
    USER_SUMMARY: (userId: number) => `/audit/user/${userId}/summary`,
    FILTERS: '/audit/filters',
  },
  // ── Module Qualité v2 ──────────────────────────────────────────────
  QUALITE_RECEPTIONS: {
    BASE: '/qualite/receptions',
    BY_ID: (id: number) => `/qualite/receptions/${id}`,
    BY_PROJET: (projetId: number) => `/qualite/receptions/projet/${projetId}`,
    SUMMARY: (projetId: number) => `/qualite/receptions/summary/projet/${projetId}`,
  },
  QUALITE_ESSAIS_LABO: {
    BASE: '/qualite/essais-labo',
    BY_ID: (id: number) => `/qualite/essais-labo/${id}`,
    BY_PROJET: (projetId: number) => `/qualite/essais-labo/projet/${projetId}`,
    BY_PROJET_MOIS: (projetId: number, mois: string) => `/qualite/essais-labo/projet/${projetId}/mois/${mois}`,
  },
  QUALITE_LEVEES_TOPO: {
    BASE: '/qualite/levees-topo',
    BY_ID: (id: number) => `/qualite/levees-topo/${id}`,
    BY_PROJET: (projetId: number) => `/qualite/levees-topo/projet/${projetId}`,
    BY_PROJET_MOIS: (projetId: number, mois: string) => `/qualite/levees-topo/projet/${projetId}/mois/${mois}`,
  },
  QUALITE_AGREMENTS: {
    BASE: '/qualite/agrements',
    BY_ID: (id: number) => `/qualite/agrements/${id}`,
    BY_PROJET: (projetId: number) => `/qualite/agrements/projet/${projetId}`,
    SUMMARY: (projetId: number) => `/qualite/agrements/summary/projet/${projetId}`,
  },
  QUALITE_EVENEMENTS: {
    BASE: '/qualite/evenements',
    BY_ID: (id: number) => `/qualite/evenements/${id}`,
    BY_PROJET: (projetId: number) => `/qualite/evenements/projet/${projetId}`,
    STATS: (projetId: number) => `/qualite/evenements/stats/projet/${projetId}`,
  },
  QUALITE_DOCUMENTS: {
    BASE: '/qualite/documents',
    BY_ID: (id: number) => `/qualite/documents/${id}`,
    VERSIONS: (id: number) => `/qualite/documents/${id}/versions`,
    DOWNLOAD: (id: number) => `/qualite/documents/${id}/download`,
  },
  QUALITE_SYNTHESE: {
    BY_PROJET_MOIS: (projetId: number, mois: string) => `/qualite/synthese/${projetId}/${mois}`,
  },
} as const

// WebSocket : même origine que l’API (dérivé de VITE_API_BASE_URL si défini)
export const WS_ENDPOINT =
  API_BASE_URL.startsWith('http')
    ? `${API_BASE_URL.replace(/\/$/, '')}/ws`
    : '/ws'
