// En prod (ex. Railway), définir VITE_API_BASE_URL (ex. https://mikaservices-production.up.railway.app/api)
export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? '/api'
export const API_VERSION = 'v1'

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGIN_POLICY: '/auth/login-policy',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    VERIFY_2FA: '/auth/verify-2fa',
    '2FA_SETUP': '/auth/2fa/setup',
    '2FA_VERIFY_SETUP': '/auth/2fa/verify-setup',
    '2FA_DISABLE': '/auth/2fa/disable',
    ME: '/users/me',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: number) => `/users/${id}`,
    BY_EMAIL: (email: string) => `/users/email/${email}`,
    ME: '/users/me',
    ME_PHOTO: '/users/me/photo',
    PHOTO_BY_ID: (id: number) => `/users/${id}/photo`,
    AUDIT_LOGS: (id: number) => `/users/${id}/audit-logs`,
    CHANGE_PASSWORD: (id: number) => `/users/${id}/password`,
  },
  EQUIPES: {
    BASE: '/equipes',
    BY_ID: (id: number) => `/equipes/${id}`,
    AFFECTATIONS_BY_USER: (userId: number) => `/equipes/affectations/user/${userId}`,
  },
  ROLES: {
    BASE: '/roles',
    ACTIVE: '/roles/active',
    BY_ID: (id: number) => `/roles/${id}`,
    BY_CODE: (code: string) => `/roles/code/${code}`,
    ADD_PERMISSION: (roleId: number, permissionId: number) => `/roles/${roleId}/permissions/${permissionId}`,
    REMOVE_PERMISSION: (roleId: number, permissionId: number) => `/roles/${roleId}/permissions/${permissionId}`,
  },
  PROJETS: {
    BASE: '/projets',
    BY_ID: (id: number) => `/projets/${id}`,
    SEARCH: '/projets/search',
    BY_STATUT: (statut: string) => `/projets/statut/${statut}`,
    BY_RESPONSABLE: (userId: number) => `/projets/responsable/${userId}`,
    COUNT_BY_STATUT: (statut: string) => `/projets/count/${statut}`,
    AVANCEMENT_ETUDES: (id: number) => `/projets/${id}/avancement-etudes`,
    PREVISIONS: (id: number) => `/projets/${id}/previsions`,
    PREVISION_BY_ID: (projetId: number, previsionId: number) => `/projets/${projetId}/previsions/${previsionId}`,
    HISTORIQUE: (id: number) => `/projets/${id}/historique`,
    SUIVI_MENSUEL: (id: number) => `/projets/${id}/suivi-mensuel`,
    SUIVI_MENSUEL_REPLACE: (id: number) => `/projets/${id}/suivi-mensuel/replace`,
  },
  SOUS_PROJETS: {
    BASE: '/sous-projets',
    BY_ID: (id: number) => `/sous-projets/${id}`,
    BY_PROJET: (projetId: number) => `/sous-projets/projet/${projetId}`,
  },
  CLIENTS: {
    BASE: '/clients',
    BY_ID: (id: number) => `/clients/${id}`,
    BY_CODE: (code: string) => `/clients/code/${code}`,
    SEARCH: '/clients/search',
  },
  POINTS_BLOQUANTS: {
    BASE: '/points-bloquants',
    BY_ID: (id: number) => `/points-bloquants/${id}`,
    BY_PROJET: (projetId: number) => `/points-bloquants/projet/${projetId}`,
    BY_STATUT: (statut: string) => `/points-bloquants/statut/${statut}`,
    BY_ASSIGNE: (userId: number) => `/points-bloquants/assigne/${userId}`,
  },
  PLANNING: {
    TACHES: '/planning/taches',
    TACHE_BY_ID: (id: number) => `/planning/taches/${id}`,
    BY_PROJET: (projetId: number) => `/planning/taches/projet/${projetId}`,
    MES_TACHES: (userId: number) => `/planning/taches/mes-taches/${userId}`,
    EN_RETARD: '/planning/taches/en-retard',
  },
  DOCUMENTS: {
    BASE: '/documents',
    BY_ID: (id: number) => `/documents/${id}`,
    BY_PROJET: (projetId: number) => `/documents/projet/${projetId}`,
    ME_CV: '/documents/me/cv',
    DOWNLOAD: (id: number) => `/documents/${id}/download`,
  },
  REPORTING: {
    DASHBOARD: '/reporting/dashboard',
    PROJET_REPORT: (projetId: number) => `/reporting/projet/${projetId}`,
  },
  MESSAGES: {
    ENVOYER: (expediteurId: number) => `/messages/${expediteurId}`,
    RECUS: (userId: number) => `/messages/recus/${userId}`,
    ENVOYES: (userId: number) => `/messages/envoyes/${userId}`,
    CONVERSATION: (userId1: number, userId2: number) => `/messages/conversation/${userId1}/${userId2}`,
    MARQUER_LU: (messageId: number, userId: number) => `/messages/${messageId}/lu/${userId}`,
    NON_LUS: (userId: number) => `/messages/non-lus/${userId}`,
    DELETE: (messageId: number) => `/messages/${messageId}`,
    ENVOYER_AVEC_PIECES: (expediteurId: number) => `/messages/${expediteurId}/with-attachments`,
    PIECE_JOINTE_DOWNLOAD: (pieceJointeId: number, userId: number) =>
      `/messages/pieces-jointes/${pieceJointeId}/download?userId=${userId}`,
    ARCHIVE: '/messages/archive',
    UNARCHIVE: '/messages/unarchive',
    ARCHIVED_PEERS: (userId: number) => `/messages/archived-peers/${userId}`,
    SUPPRESS_FOR_ME: (messageId: number) => `/messages/${messageId}/suppress-for-me`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    MES_NOTIFICATIONS: (userId: number) => `/notifications/mes-notifications/${userId}`,
    NON_LUES: (userId: number) => `/notifications/non-lues/${userId}`,
    MARQUER_LUE: (notifId: number, userId: number) => `/notifications/${notifId}/lu/${userId}`,
    TOUT_LU: (userId: number) => `/notifications/tout-lu/${userId}`,
    COUNT: (userId: number) => `/notifications/count/${userId}`,
    DELETE: (notifId: number) => `/notifications/${notifId}`,
  },
  SECURITE: {
    INCIDENTS: '/securite/incidents',
    INCIDENT_BY_ID: (id: number) => `/securite/incidents/${id}`,
    INCIDENTS_BY_PROJET: (projetId: number) => `/securite/incidents/projet/${projetId}`,
    RISQUES: '/securite/risques',
    RISQUE_BY_ID: (id: number) => `/securite/risques/${id}`,
    RISQUES_BY_PROJET: (projetId: number) => `/securite/risques/projet/${projetId}`,
    ACTIONS: '/securite/actions',
    ACTION_BY_ID: (id: number) => `/securite/actions/${id}`,
    ACTIONS_BY_INCIDENT: (incidentId: number) => `/securite/actions/incident/${incidentId}`,
    ACTIONS_EN_RETARD: '/securite/actions/en-retard',
    SUMMARY: (projetId: number) => `/securite/summary/projet/${projetId}`,
  },
  REUNIONS_HEBDO: {
    BASE: '/reunions-hebdo',
    BY_ID: (id: number) => `/reunions-hebdo/${id}`,
    BY_STATUT: (statut: string) => `/reunions-hebdo/statut/${statut}`,
    POINTS_PROJET: (reunionId: number) => `/reunions-hebdo/${reunionId}/points-projet`,
    POINT_PROJET: (reunionId: number, pointId: number) => `/reunions-hebdo/${reunionId}/points-projet/${pointId}`,
  },
  QUALITE: {
    CONTROLES: '/qualite/controles',
    CONTROLE_BY_ID: (id: number) => `/qualite/controles/${id}`,
    CONTROLES_BY_PROJET: (projetId: number) => `/qualite/controles/projet/${projetId}`,
    NON_CONFORMITES: '/qualite/non-conformites',
    NC_BY_ID: (id: number) => `/qualite/non-conformites/${id}`,
    NC_BY_CONTROLE: (controleId: number) => `/qualite/non-conformites/controle/${controleId}`,
    NC_EN_RETARD: '/qualite/non-conformites/en-retard',
    SUMMARY: (projetId: number) => `/qualite/summary/projet/${projetId}`,
  },
} as const

// WebSocket : même origine que l’API (dérivé de VITE_API_BASE_URL si défini)
export const WS_ENDPOINT =
  API_BASE_URL.startsWith('http')
    ? `${API_BASE_URL.replace(/\/$/, '')}/ws`
    : '/ws'
